In [1]:
# BoW 모델 직접 구현 (TF-IDF) (wikipiedia)

In [2]:
# 구두점 제거 -> 소문자화 -> 토큰화 -> 개수

import re, string
import numpy as np
from collections import Counter

punc_regex = re.compile('[{}]'.format(re.escape(string.punctuation)))

def strip_punc(corpus):
    return punc_regex.sub('', corpus)

doc = "Apples rule. Apples are the best. Truly, they are. Truly... Truly"

doc = strip_punc(doc)
counter = Counter(doc.lower().split())
descriptor = np.array([counter[word] for word in sorted(counter)], dtype=float)
print(sorted(counter))
print(descriptor)

['apples', 'are', 'best', 'rule', 'the', 'they', 'truly']
[2. 2. 1. 1. 1. 1. 3.]


In [4]:
def to_counter(doc):
    return Counter(strip_punc(doc).lower().split())

def to_vocab(counters):
    vocab = set()
    for counter in counters:
        vocab.update(counter)
    return sorted(vocab)

def to_tf(counter, vocab):
    return np.array([counter[word] for word in vocab], dtype=float)

In [5]:
doc_1 = "I am a dog."
doc_2 = "I am a cat!"
doc_3 = "I am not a dog"
doc_4 = "I am not a cat, am I!?!"

word_counts = [to_counter(doc) for doc in [doc_1, doc_2, doc_3, doc_4]]
bag = to_vocab(word_counts)
tfs = np.vstack([to_tf(counter, bag) for counter in word_counts])
print(bag)
print(tfs)

['a', 'am', 'cat', 'dog', 'i', 'not']
[[1. 1. 0. 1. 1. 0.]
 [1. 1. 1. 0. 1. 0.]
 [1. 1. 0. 1. 1. 1.]
 [1. 2. 1. 0. 2. 1.]]


In [22]:
# 상위 k개 추출로 함수 변경

def to_vocab(counters, k=None):
    vocab = Counter()
    for counter in counters:
        vocab.update(counter)
    
    return sorted([word for (word, cnt) in vocab.most_common(k)])

In [25]:
# wiki에서 상위 50개 빈출단어 출력

path = "../../dataset/wikipedia2text-extracted.txt"
with open(path, "rb") as f:
    wiki = f.read().decode()

wiki_count = to_counter(wiki)
wik = to_vocab([wiki_count], k=50)
print(wik)

['a', 'after', 'all', 'also', 'an', 'and', 'are', 'as', 'at', 'be', 'been', 'but', 'by', 'first', 'for', 'from', 'had', 'has', 'have', 'he', 'his', 'in', 'into', 'is', 'it', 'its', 'many', 'more', 'most', 'new', 'not', 'of', 'on', 'one', 'or', 'other', 'some', 'such', 'that', 'the', 'their', 'there', 'they', 'this', 'to', 'was', 'were', 'which', 'who', 'with']


In [ ]:
def to_vocab(counters, k=None, stop_words=tuple()):
    